add ci check-package-json

diff --git a/.github/workflows/.github-ci.yml b/.github/workflows/.github-ci.yml
--- a/.github/workflows/.github-ci.yml
+++ b/.github/workflows/.github-ci.yml
@@ -1,4 +1,4 @@
-name: Node.js CI
+name: build
 
 on:
   push:
@@ -6,6 +6,21 @@ on:
       - main
 
 jobs:
+  check-package-json:
+    runs-on: ubuntu-latest
+
+    steps:
+    - name: Checkout code
+      uses: actions/checkout@v2
+
+    - name: Check if package.json exists
+      run: |
+        if [ -f "package.json" ]; then
+          echo "package.json found"
+        else
+          echo "Error: package.json not found"
+          exit 1
+        fi
   build:
 
     runs-on: ubuntu-latest
@@ -17,7 +32,7 @@ jobs:
     - name: Setup Node.js
       uses: actions/setup-node@v2
       with:
-        node-version: '20' # Cambia la versión de Node.js si es necesario
+        node-version: '20'
 
     - name: Install dependencies
       run: npm install
